version: '3.7'
services:
  zookeeper:
    container_name: zookeeper_poc
    image: zookeeper:3.5.4-beta
    ports:
    - "2181:2181"
  kafka:
    container_name: kafka_poc
    image: wurstmeister/kafka:0.11.0.0
    ports:
    - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: 127.0.0.1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181